server:
  port: 30000
application:
  version: 1.5.2.RELEASE
spring:
  application:
    name: eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false